definitions:
  request.BuyRequest:
    properties:
      powerUpId:
        type: string
      quantity:
        type: integer
    required:
    - powerUpId
    - quantity
    type: object
  request.EndGameRequest:
    properties:
      coinsCollected:
        type: integer
      distance:
        type: integer
    required:
    - coinsCollected
    - distance
    type: object
  request.ForgotPassRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.PaymentRequest:
    properties:
      cartId:
        type: string
      paymentType:
        type: string
    type: object
  request.PowerUpRequest:
    properties:
      powerUpId:
        type: string
    required:
    - powerUpId
    type: object
  request.RegisterRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 16
        minLength: 8
        type: string
      playerName:
        type: string
    required:
    - email
    - password
    - playerName
    type: object
  request.UpdateNameRequest:
    properties:
      playerName:
        type: string
    required:
    - playerName
    type: object
  request.UpdatePasswordRequest:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  response.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.Success:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is the api doucmentation for subway surfers
  title: Subway surfers api
  version: "1.0"
paths:
  /buy-powerup:
    post:
      consumes:
      - application/json
      description: Details of the power up bought
      parameters:
      - description: Power Up bought details
        in: body
        name: Details
        required: true
        schema:
          $ref: '#/definitions/request.BuyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Powerups
  /collect-reward:
    get:
      consumes:
      - application/json
      description: Collet reward handler
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Daily Reward
  /end-game:
    post:
      consumes:
      - application/json
      description: Ends the game
      parameters:
      - description: Players record after game end
        in: body
        name: gameDetails
        required: true
        schema:
          $ref: '#/definitions/request.EndGameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Game
  /forgot-password:
    post:
      consumes:
      - application/json
      description: Forgot password
      parameters:
      - description: Players registers email
        in: body
        name: playerEmail
        required: true
        schema:
          $ref: '#/definitions/request.ForgotPassRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Authentication
  /login:
    post:
      consumes:
      - application/json
      description: Log in a player
      parameters:
      - description: Details of the player
        in: body
        name: playerDetails
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Authentication
  /logout:
    delete:
      consumes:
      - application/json
      description: Logs out a player
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Authentication
  /make-payment:
    post:
      consumes:
      - application/json
      description: Make payment
      parameters:
      - description: payment details of the player
        in: body
        name: paymentDetails
        required: true
        schema:
          $ref: '#/definitions/request.PaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Payment
  /register-player:
    post:
      consumes:
      - application/json
      description: Register a player
      parameters:
      - description: Details of the player
        in: body
        name: playerDetails
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Authentication
  /reset-password:
    post:
      consumes:
      - application/json
      description: Reset password
      parameters:
      - description: Players new password
        in: body
        name: NewPassword
        required: true
        schema:
          $ref: '#/definitions/request.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Authentication
  /show-cart:
    get:
      consumes:
      - application/json
      description: Show cart to the player
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Cart
  /show-leaderboard:
    get:
      consumes:
      - application/json
      description: Shows the leaderboard
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Leaderboard
  /show-player:
    get:
      consumes:
      - application/json
      description: Show player details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Player
  /show-powerups:
    post:
      consumes:
      - application/json
      description: Show Power ups
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Powerups
  /update-name:
    patch:
      consumes:
      - application/json
      description: Updates the player name of the player
      parameters:
      - description: New name of the player
        in: body
        name: newName
        required: true
        schema:
          $ref: '#/definitions/request.UpdateNameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Authentication
  /update-pass:
    patch:
      consumes:
      - application/json
      description: Updates the password of the player
      parameters:
      - description: New password of the player
        in: body
        name: newPassword
        required: true
        schema:
          $ref: '#/definitions/request.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Authentication
  /use-powerup:
    post:
      consumes:
      - application/json
      description: Details of the power up used
      parameters:
      - description: Power Up used details
        in: body
        name: Details
        required: true
        schema:
          $ref: '#/definitions/request.PowerUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      tags:
      - Powerups
swagger: "2.0"
